version: "3.9"

networks:
  overlay:

services:

  web:
    build: app
    networks:
      - overlay
    ports:
      - "8080"
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

  pinger:
    depends_on:
      - web
    build: pinger
    networks:
      - overlay
